#!/bin/sh

# set bg
feh --no-fehbg --bg-fill '/home/francis/wallpapers/carina-nebula.jpg'
# force regen of font cache
fc-cache -f
# start polybar
if pgrep polybar; then
    pkill polybar
fi
polybar --config=~/.config/polybar/config.ini -r bar &

# connect to wifi
# nmcli device wifi con COLEY_DRIVEWAY
