# Rust
. "$HOME/.cargo/env"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/francis/google-cloud-sdk/path.zsh.inc' ]; then . '/home/francis/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/francis/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/francis/google-cloud-sdk/completion.zsh.inc'; fi

# Default text editors
export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim

export PATH=$HOME/scripts:$PATH

