source ~/.bashrc
export PS1="💰 \[\e[91m\]▸\[\e[m\] "
# export PS1="💰 ◂"
# export PS1="\[\e[91m\]λ\[\e[m\]"
# export CLICOLOR=1
# export LSCOLORS=ExFxBxDxCxegedabagacad

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
