source ~/.bashrc
# export PS1="💰 \[\e[91m\]▸\[\e[m\] "
# export PS1="💰 ◂"
# export PS1="\[\e[91m\]λ\[\e[m\]"
# export CLICOLOR=1
# export LSCOLORS=ExFxBxDxCxegedabagacad

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
# PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
